export const VALIDATION_LIMITS = {
  USER: {
    MIN_USERNAME_LENGTH: 2,
    MAX_USERNAME_LENGTH: 50,
    MIN_FIRSTNAME_LENGTH: 1,
    MAX_FIRSTNAME_LENGTH: 50,
    MIN_LASTNAME_LENGTH: 1,
    MAX_LASTNAME_LENGTH: 50,
    MAX_EMAIL_LENGTH: 255,
    MIN_PASSWORD_LENGTH: 8,
    MAX_PASSWORD_LENGTH: 100,
  },
} as const;
